[workspace]
members = [
    "comms-manager/",
    "ecu/engine-controller",
    "fcu/flight-controller",
    "hal",
    "mission-ctrl/mission-ctrl-server",
    "shared",
    "simulation/core/software-in-loop",
    "streamish",
]

exclude = [
    "ecu/targets/stm32f407",
    "fcu/targets/fcu-stm32f407",
]